import { Backcompat } from "../types";

export const vcard: Backcompat = {
  type: ["h-card"],
  properties: {
    fn: "p-name",
    url: "u-url",
    org: "p-org",
    adr: "p-adr",
    tel: "p-tel",
    title: "p-job-title",
    email: "u-email",
    photo: "u-photo",
    agent: "p-agent",
    "family-name": "p-family-name",
    "given-name": "p-given-name",
    "additional-name": "p-additional-name",
    "honorific-prefix": "p-honorific-prefix",
    "honorific-suffix": "p-honorific-suffix",
    key: "p-key",
    label: "p-label",
    logo: "u-logo",
    mailer: "p-mailer",
    nickname: "p-nickname",
    note: "p-note",
    sound: "u-sound",
    geo: "p-geo",
    bday: "dt-bday",
    class: "p-class",
    rev: "p-rev",
    role: "p-role",
    "sort-string": "p-sort-string",
    tz: "p-tz",
    uid: "u-uid",
  },
  rels: {
    tag: "p-category",
  },
};
